#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <hey>;
!slot <new>;
!slot <item>;
!slot <room>;
!slot <box>;
!slot <del>;
!slot <please>;
!slot <user>;
!slot <items>;
!slot <been>;
!slot <put>;
!slot <done>;
!slot <rooms>;
!slot <s>;
!slot <boxes>;
!slot <prep>;
!slot <where>;
!slot <question>;
!slot <delete>;
!start <instruction>;
<instruction>:[<hey>][<please>]<ready>;
<ready>:<subject><operation>|<change>;
<change>:[<user>]<do><object>;
<do>:<del>|<new>;
<object>:<item>|<room>|<box>;
<subject>:<user><items>;
<operation>:<delete>|[<been>]<put><end>;
<end>:<store>|<find>;
<store>:[<done>]<position>;
<position>:<rooms>[<s>]<boxes>[<prep>][s];
<find>:<where>[<question>];
<hey>:东东|东东东东|小东小东|你好小东|你好|小东;
<new>:新增|新建;
<item>:物件|物品|物体;
<room>:房间|房屋;
<box>:储物空间|存储空间|储存空间|空间;
<del>:删除|删掉;
<please>:请问|请问你|你知道|请问你知道|请;
<user>:我的|我把|我|我想|我想把|我要|把|把我的|我需要|帮我把|帮我;
<items>:钥匙;
<been>:被;
<put>:放在|放进|装进|装在|放置在|存在|留在|在|丢在|丢进;
<done>:了;
<rooms>:主卧;
<s>:的;
<boxes>:盒子;
<prep>:里|上|下|中;
<where>:哪里|哪|哪个地方|哪个位置;
<question>:呢|吗|了呢|了吗;
<delete>:删除|拿出来|的位置删除掉|删除掉;